# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bef71de95b2cd6b0d80baf8ad71d5f8d057d8614a44d648bf3df27e7fe85449f3715ede5d9f35d07441647eb153a488d87a1899857a9da1770f85d1a7d415e7

test:
  secret_key_base: d60020dfc465c34455ea129221ac9dc11c8edf7916d65e5a274bb863fbbd6a847fab1c4a52acced486799a186098b65dad79f8baad4ee876e3201afbf163f884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
